DIPO_INVESTAMA/Controllers/MasterAccountController.cs
using DIPO_INVESTAMA.App_Start;
using DIPO_INVESTAMA.Entity;
using DIPO_INVESTAMA.Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DIPO_INVESTAMA.Controllers
{
    public class MasterAccountController : Controller
    {
        // GET: MasterAccount
        [CheckAuthorize(Roles = "Account")]
        public ActionResult Index()
        {
            return View(AccountBusinessLogic.getInstance().ListMasterAccount());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(sp_AccountSelect_Result model)
        {
            if (AccountBusinessLogic.getInstance().CreateAccount(model) == -1)
            {
                TempData["Success"] = "Account was successfully inserted";
            }
            else
            {
                TempData["Error"] = "Account was unsuccessfully inserted";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id)
        {
            sp_AccountSelect_Result model = new sp_AccountSelect_Result();
            var accountData = AccountBusinessLogic.getInstance().getAccountById(id);
            model.AccountId = accountData.AccountId;
            model.AccountName = accountData.AccountName;
            model.AccountNo = accountData.AccountNo;
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(sp_AccountSelect_Result model)
        {
            if (AccountBusinessLogic.getInstance().UpdateAccount(model) == -1)
            {
                TempData["Success"] = "Account was successfully updated";
            }
            else
            {
                TempData["Error"] = "Account was unsuccessfully updated";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            try
            {
                if (AccountBusinessLogic.getInstance().DeleteAccount(id) == -1)
                {
                    TempData["Success"] = "Account was successfully deleted";
                }
                else
                {
                    TempData["Error"] = "Account was unsuccessfully deleted";
                }
            }
            catch (Exception e)
            {
                TempData["Error"] = "Account was unsuccessfully deleted";
                Logging.getInstance().CreateLogError(e);
            }
            return RedirectToAction("Index");
        }
    }
}

DIPO_INVESTAMA/Views/MasterAccount/Create.cshtml
@model DIPO_INVESTAMA.Entity.sp_AccountSelect_Result
@using (Html.BeginForm("Create", "MasterAccount", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="modal-content body-box-primary">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body Poppins-Regular font-white">
            <div class="container">
                <div class="row">
                    @*<div class="col-md-4">
                        <label>Account No</label>
                        @Html.TextBoxFor(model => model.AccountNo, new { @class = "form-control", @placeholder = "Account No", autocomplete = "off", required = "required" })
                    </div>*@
                    <div class="col-md-4">
                        <label>Account Name</label>
                        @Html.TextBoxFor(model => model.AccountName, new { @class = "form-control", @placeholder = "Account Name", autocomplete = "off", required = "required" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a type="button" class="btn btn-default" href="@Url.Action("Index","MasterAccount")">Kembali</a>
        </div>
    </div>
}

DIPO_INVESTAMA/Views/MasterAccount/Edit.cshtml
@model DIPO_INVESTAMA.Entity.sp_AccountSelect_Result
@using (Html.BeginForm("Edit", "MasterAccount", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.AccountId)
    <div class="modal-content body-box-primary">
        <div class="modal-header">
            <button type="button" class="close body-close" data-dismiss="modal">×</button>
            <h3 class="Poppins-Bold font-white">MasterAccount / Edit</h3>
        </div>
        <div class="modal-body Poppins-Regular font-white">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <label>Account No</label>
                        @Html.TextBoxFor(model => model.AccountNo, new { @class = "form-control", @placeholder = "Account No", autocomplete = "off", required = "required", @disabled="disabled" })
                        @Html.HiddenFor(model => model.AccountNo)
                    </div>
                    <div class="col-md-4">
                        <label>Account Name</label>
                        @Html.TextBoxFor(model => model.AccountName, new { @class = "form-control", @placeholder = "Account Name", autocomplete = "off", required = "required" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a type="button" class="btn btn-default" href="@Url.Action("Index","MasterAccount")">Kembali</a>
        </div>
    </div>
}

DIPO_INVESTAMA/Views/MasterAccount/Index.cshtml
@model DIPO_INVESTAMA.Models.PagedList<DIPO_INVESTAMA.Entity.sp_AccountSelect_Result>

@if (TempData["Error"] != null)
{
    <div class="alert alert-warning" style="margin:10px">
        <p><i class="fa fa-warning"></i> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success" style="margin:10px">
        <strong>Success!</strong> @TempData["Success"].ToString()
    </div>
}
<div class="box box-primary body-box-primary">
    <div class="box-header with-border">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="box-title Poppins-Bold font-white">Master Account</h3>
            </div>
            <div class="col-lg-6" align="right">
                <a style="cursor:pointer;" href="@Url.Action("Create","MasterAccount")">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form">
        <div class="box-body">
            <table class="table Poppins-Regular font-white" id="example1">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Account No")
                        </th>
                        <th>
                            @Html.DisplayName("Account Name")
                        </th>
                        <th>

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Content.Count; i++)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Content[i].AccountNo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Content[i].AccountName)
                            </td>
                            <td>
                                <a style="cursor:pointer" href="@Url.Action("Edit","MasterAccount", new { id = Model.Content[i].AccountId})">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </a>
                                <a style="cursor:pointer" value="loop" onclick="ShowModal(@i)">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                                <div id="modalBank_@i" class="modal fade" tabindex="-1" data-keyboard="false" data-backdrop="static">
                                    <div class="modal-dialog">
                                        <div class="modal-content body-modal-content" style="width:700px;">
                                            <div class="modal-header">
                                                <h4 class="modal-title" style="float:left; width:100px; background-color:none"> <i class="fa fa-trash"></i> Delete</h4>
                                                <button type="button" class="close body-close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                Do you really to delete @Html.DisplayFor(modelItem => Model.Content[i].AccountNo) ??
                                            </div>
                                            <div class="modal-footer">
                                                <a data-toggle="tooltip" title="Delete" href="@Url.Action("Delete", "MasterAccount", new { id = Model.Content[i].AccountId })" class="btn btn-primary"><i class="fa fa-trash"></i> Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </form>
</div>

<script>
    function ShowModal(idx) {
        $("#modalBank_" + idx).modal('show');
    }

    function HideModal(idx) {
        $("#modalBank_" + idx).modal('hide');
    }

</script>