DIPO_INVESTAMA/Controllers/MenuRestrictionController.cs
using DIPO_INVESTAMA.App_Start;
using DIPO_INVESTAMA.Entity;
using DIPO_INVESTAMA.Logic;
using DIPO_INVESTAMA.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DIPO_INVESTAMA.Controllers
{
    public class MenuRestrictionController : Controller
    {
        //[CheckAuthorize(Roles = "Menu Restriction")]
        public ActionResult Index()
        {
            return View(MenuRestrictionBusinessLogic.getInstance().ListMenuRestriction());
        }

        public ActionResult Create()
        {
            ViewBag.RoleList = common.ToSelectList(RoleBusinessLogic.getInstance().getRoleDDL(), "ID", "NAME", string.Empty);
            ViewBag.MenuList = common.ToSelectList(MenuRestrictionBusinessLogic.getInstance().getMenuDDL(""), "ID", "NAME", string.Empty);
            return View();
        }

        [HttpPost]
        public ActionResult Create(sp_MenuRestrictionSelect_Result model)
        {
            if (MenuRestrictionBusinessLogic.getInstance().CreateMenuRestriction(model) == -1)
            {
                TempData["Success"] = "Menu Restriction was successfully inserted";
            }
            else
            {
                TempData["Error"] = "Menu Restriction was unsuccessfully inserted";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id)
        {
            sp_MenuRestrictionSelect_Result model = new sp_MenuRestrictionSelect_Result();
            var menuData = MenuRestrictionBusinessLogic.getInstance().getMenuById(id);
            model.RestrictionId = menuData.RestrictionId;
            model.MenuId = menuData.MenuId;
            model.RoleId = menuData.RoleId;

            ViewBag.RoleList = common.ToSelectList(RoleBusinessLogic.getInstance().getRoleDDL(), "ID", "NAME", model.RoleId);
            ViewBag.MenuList = common.ToSelectList(MenuRestrictionBusinessLogic.getInstance().getMenuDDL(model.RoleId), "ID", "NAME", model.MenuId);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(sp_MenuRestrictionSelect_Result model)
        {
            if (MenuRestrictionBusinessLogic.getInstance().UpdateMenuRestriction(model) == -1)
            {
                TempData["Success"] = "Menu Restriction was successfully updated";
            }
            else
            {
                TempData["Error"] = "Menu Restriction was unsuccessfully updated";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            if (MenuRestrictionBusinessLogic.getInstance().DeleteMenuRestriction(id) == -1)
            {
                TempData["Success"] = "Menu Restriction was successfully deleted";
            }
            else
            {
                TempData["Error"] = "Menu Restriction was unsuccessfully deleted";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult MenuDDL(string roleId)
        {
            var menuList = common.ToSelectList(MenuRestrictionBusinessLogic.getInstance().getMenuDDL(roleId), "ID", "NAME", "");
            return Json(menuList,JsonRequestBehavior.AllowGet);
        }
    }
}  

DIPO_INVESTAMA/Controllers/MenuRestrictionsController.cs
using DIPO_INVESTAMA.App_Start;
using DIPO_INVESTAMA.Entity;
using DIPO_INVESTAMA.Logic;
using DIPO_INVESTAMA.Models;
using DIPO_INVESTAMA.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace DIPO_INVESTAMA.Controllers
{
    public class MenuRestrictionsController : Controller
    {
        DIPO_INVESTAMAEntities _db = new DIPO_INVESTAMAEntities();
        // GET: MenuRestrictions
        [CheckAuthorize(Roles = "Menu Restriction")]
        public ActionResult Index()
        {
            return View(MenuRestrictionsBusinessLogic.getInstance().ListMenuRestriction());
        }
        [CheckAuthorize(Roles = "Menu Restriction")]
        public ActionResult Create()
        {
            PrivilegeViewModels model = new PrivilegeViewModels();
            model.Parent = null;
            model.Menu = MenuList("0", SessionManager.userId());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PrivilegeViewModels Privilege)
        {
            //check data in database if already exist skip
            var CheckData = _db.Roles.Where(x => x.RoleName == Privilege.Parent.RoleName).ToList();
            if (CheckData.Count() == 0)
            {
                if (ModelState.IsValid)
                {
                    MenuRestrictionsBusinessLogic.getInstance().InsertRole(Privilege.Parent.RoleName);
                    var privilegeId = _db.Roles.Where(a => a.RoleName == Privilege.Parent.RoleName).Single().RoleId;
                    MenuRestrictionsBusinessLogic.getInstance().SaveMenu(Privilege.Menu, privilegeId);
                    TempData["Success"] = "Success saving Data for " + Privilege.Parent.RoleName;
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Error"] = "Name :" + Privilege.Parent.RoleName + " already exist!";
            }

            return View(Privilege);
        }
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrivilegeViewModels model = new PrivilegeViewModels();
            model.Parent = _db.Roles.Find(id);
            model.Menu = MenuEdit("0", id, SessionManager.userId());

            if (model.Parent == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PrivilegeViewModels Privilege)
        {
            if (Privilege.Parent.RoleName == null)
            {
                TempData["Error"] = "Name :" + Privilege.Parent.RoleName + " not exist!";
            }
            //check data in database if already exist skip
            var CheckData = _db.Roles.Where(x => x.RoleName == Privilege.Parent.RoleName && x.RoleId != Privilege.Parent.RoleId).ToList();
            if (CheckData.Count() == 0)
            {
                if (ModelState.IsValid)
                {
                    MenuRestrictionsBusinessLogic.getInstance().UpdateRole(Privilege.Parent.RoleId, Privilege.Parent.RoleName);
                    var dt = (from c in _db.MenuRestrictions
                              where c.RoleId == Privilege.Parent.RoleId
                              select c).ToList();
                    foreach (var item in dt)
                    {
                        MenuRestriction menuRestriction = new MenuRestriction();
                        menuRestriction.RestrictionId = item.RestrictionId;
                        menuRestriction.MenuId = item.RestrictionId;
                        menuRestriction.RoleId = item.RoleId;
                        menuRestriction.IsRead = item.IsRead;
                        MenuRestrictionsBusinessLogic.getInstance().UpdateMenuRestriction(menuRestriction);
                    }
                    MenuRestrictionsBusinessLogic.getInstance().SaveMenu(Privilege.Menu, Privilege.Parent.RoleId);
                    TempData["Success"] = "Success Editing Data for " + Privilege.Parent.RoleName;
                    return RedirectToAction("Index");
                }
            }
            else
            {
                TempData["Error"] = "Name :" + Privilege.Parent.RoleName + " already exist!";
            }

            return View(Privilege);
        }
        public List<MenuViewModels> MenuEdit(string parentId, string privilegeId, string userId)
        {
            List<MenuViewModels> listViewModel = new List<MenuViewModels>();
            List<Menu> listMenu = new List<Menu>();
            listMenu = MenuRestrictionsBusinessLogic.getInstance().GetPrivilegeTree(userId, privilegeId, parentId);
            foreach (Menu itemMenu in listMenu)
            {
                MenuRestrictionsController MeMC = new MenuRestrictionsController();
                MenuViewModels Menu = new MenuViewModels();
                Menu.Parent = itemMenu;
                Menu.Checked = Convert.ToBoolean(itemMenu.IsRead);
                Menu.Child = MeMC.MenuEdit(itemMenu.MenuId, privilegeId, userId);
                listViewModel.Add(Menu);
            }

            return listViewModel;
        }

        public List<MenuViewModels> MenuList(string parentId, string userId)
        {
            List<MenuViewModels> model = new List<MenuViewModels>();
            List<Menu> listMenu = new List<Menu>();
            var menuData = (from c in _db.Menus
                       join b in _db.MenuRestrictions on c.MenuId equals b.MenuId
                       join d in _db.Roles on b.RoleId equals d.RoleId
                       join e in _db.Users on b.RoleId equals e.RoleId
                       where c.ParentId == parentId && e.UserId == userId
                       select new { c, b }).OrderBy(x => x.c.Opt).ToList();

            foreach (var itm in menuData)
            {
                var m = new Menu
                {
                    MenuId = itm.c.MenuId,
                    Action = itm.c.Action,
                    Controller = itm.c.Controller,
                    Descriptions = itm.c.Descriptions,
                    Icon = itm.c.Icon,
                    MenuName = itm.c.MenuName,
                    ParentId = itm.c.ParentId,
                    ShowMenu = itm.c.ShowMenu,
                    Opt = itm.c.Opt
                };
                listMenu.Add(m);
            }

            foreach (Menu itemMenu in listMenu)
            {
                MenuRestrictionsController MeMC = new MenuRestrictionsController();
                MenuViewModels menuViewModels = new MenuViewModels();
                menuViewModels.Checked = false;
                menuViewModels.Parent = itemMenu;
                menuViewModels.Child = MeMC.MenuList(itemMenu.MenuId, userId);
                model.Add(menuViewModels);
            }

            return model;
        }
    }
}

DIPO_INVESTAMA/Views/MenuRestriction/Create.cshtml
@model DIPO_INVESTAMA.Entity.sp_MenuRestrictionSelect_Result
@using (Html.BeginForm("Create", "MenuRestriction", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="modal-content body-box-primary">
        <div class="modal-header">
            <button type="button" class="close body-close" data-dismiss="modal">×</button>
            <h3 class="Poppins-Bold font-white">MenuRestriction / Create</h3>
        </div>
        <div class="modal-body Poppins-Regular font-white">
            <div class="">
                <div class="row">
                    <div class="col-md-6">
                        <label>Role Name</label>
                        @Html.DropDownListFor(model => model.RoleId, ViewBag.RoleList as SelectList, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6">
                        <label>Menu</label>
                        @Html.DropDownListFor(model => model.MenuId, ViewBag.MenuList as SelectList, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a type="button" class="btn btn-default" href="@Url.Action("Index","MenuRestriction")">Kembali</a>
        </div>
    </div>
}

<script>
    $(function () {
        DisableDropDown("#MenuId");

        $('#RoleId').change(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("MenuDDL", "MenuRestriction")",
                data: { roleId: $('#RoleId').val() },
                success: function (response) {
                    DisableDropDown("#MenuId");
                    PopulateDropDown('#MenuId',response)
                },
                error: function (response) {
                    alert(response)
                }
            });
        });
    });
</script>

DIPO_INVESTAMA/Views/MenuRestriction/Edit.cshtml
@model DIPO_INVESTAMA.Entity.sp_MenuRestrictionSelect_Result
@using (Html.BeginForm("Edit", "MenuRestriction", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.RestrictionId)
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <label>Role Name</label>
                        @Html.DropDownListFor(model => model.RoleId, ViewBag.RoleList as SelectList, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6">
                        <label>Menu</label>
                        @Html.DropDownListFor(model => model.MenuId, ViewBag.MenuList as SelectList, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a type="button" class="btn btn-default" href="@Url.Action("Index","MenuRestriction")">Kembali</a>
        </div>
    </div>
}

<script>
    $(function () {
        $('#RoleId').change(function () {
            $.ajax({
                type: "POST",
                url: "@Url.Action("MenuDDL", "MenuRestriction")",
                data: { roleId: $('#RoleId').val() },
                success: function (response) {
                    DisableDropDown("#MenuId");
                    PopulateDropDown('#MenuId',response)
                },
                error: function (response) {
                    alert(response)
                }
            });
        });
    });
</script>

DIPO_INVESTAMA/Views/MenuRestriction/Index.cshtml
@model DIPO_INVESTAMA.Models.PagedList<DIPO_INVESTAMA.Entity.sp_MenuRestrictionSelect_Result>

@if (TempData["Error"] != null)
{
    <div class="alert alert-warning" style="margin:10px">
        <p><i class="fa fa-warning"></i> @TempData["Error"].ToString()</p>
    </div>
}
@if (TempData["Success"] != null)
{
    <div class="alert alert-success" style="margin:10px">
        <strong>Success!</strong> @TempData["Success"].ToString()
    </div>
}
<div class="box box-primary body-box-primary">
    <div class="box-header with-border">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="box-title Poppins-Bold font-white">Menu Restrictions</h3>
            </div>
            <div class="col-lg-6" align="right">
                <a style="cursor:pointer;" href="@Url.Action("Create","MenuRestriction")">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form">
        <div class="box-body">
            <table class="table Poppins-Regular font-white" id="example1">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Menu Name")
                        </th>
                        <th>
                            @Html.DisplayName("Role Name")
                        </th>
                        <th>

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Content.Count; i++)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Content[i].MenuName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Content[i].RoleName)
                            </td>
                            <td>
                                @*<a style="cursor:pointer" href="@Url.Action("Edit","MenuRestriction", new { id = Model.Content[i].RestrictionId})">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </a>*@
                                <a style="cursor:pointer" value="loop" onclick="ShowModal(@i)">
                                    <i class="glyphicon glyphicon-trash"></i>
                                </a>
                                <div id="modal_@i" class="modal fade" tabindex="-1" data-keyboard="false" data-backdrop="static">
                                    <div class="modal-dialog">
                                        <div class="modal-content body-modal-content" style="width:700px;">
                                            <div class="modal-header">
                                                <h4 class="modal-title" style="float:left; width:100px; background-color:none"> <i class="fa fa-trash"></i> Delete</h4>
                                                <button type="button" class="close body-close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                Do you really to delete @Html.DisplayFor(modelItem => Model.Content[i].MenuName) for Role @Html.DisplayFor(modelItem => Model.Content[i].RoleName) ??
                                            </div>
                                            <div class="modal-footer">
                                                <a data-toggle="tooltip" title="Delete" href="@Url.Action("Delete", "MenuRestriction", new { id = Model.Content[i].RestrictionId })" class="btn btn-primary"><i class="fa fa-trash"></i> Delete</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </form>
</div>

<script>
    function ShowModal(idx) {
        $("#modal_" + idx).modal('show');
    }

    function HideModal(idx) {
        $("#modal_" + idx).modal('hide');
    }

</script>