DIPO_INVESTAMA/Models/HistoryViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DIPO_INVESTAMA.Models
{
    public class HistoryViewModels
    {
        public string PettyCashId { get; set; }
        public string Date { get; set; }
        public string Account { get; set; }
        public string BankAccount { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string Origin { get; set; }
        public string CashIn { get; set; }
        public string CashOut { get; set; }
        public string Balance { get; set; }
        public string SortBy { get; set; }
        public string Maker { get; set; }
        public string Department { get; set; }
        public string CheckedBy { get; set; }
        public string ApprovalBy { get; set; }
        public string RejectedBy { get; set; }
        public PagedList<HistoryViewModels> TodaysJournal { get; set; }
    }
}

DIPO_INVESTAMA/Controllers/HistoryController.cs
using DIPO_INVESTAMA.App_Start;
using DIPO_INVESTAMA.Logic;
using DIPO_INVESTAMA.Models;
using DIPO_INVESTAMA.Utils;
using iTextSharp.text;
using iTextSharp.text.pdf;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DIPO_INVESTAMA.Controllers
{
    public class HistoryController : Controller
    {
        private string fontPath = ConfigurationManager.AppSettings["FontPath"];
        // GET: Output
        [CheckAuthorize(Roles = "Log")]
        public ActionResult Index(string sd, string ed, string acc, string bnk, string srt)
        {
            HistoryViewModels model = new HistoryViewModels();

            string strDate = DateTime.Now.AddMonths(-1).ToString("MM/dd/yyyy");
            string endDate = DateTime.Now.ToString("MM/dd/yyyy");

            model.Date = string.Format("{0}{1}", sd == null ? strDate : sd, ed == null ? " - " + endDate : " - " + ed);
            model.Account = acc == null ? string.Empty : acc;
            model.BankAccount = bnk == null ? string.Empty : bnk;
            model.SortBy = srt == null ? string.Empty : srt;
            model.TodaysJournal = Journals(model);

            ViewBag.AccountList = common.ToSelectList(AccountDetailsBusinessLogic.getInstance().getAccountDetailDDL(), "ID", "NAME", string.Empty);
            ViewBag.BankFacilityList = common.ToSelectList(BankFacilityBusinessLogic.getInstance().getBankFacilityDDL(), "ID", "NAME", model.BankAccount);
            ViewBag.SortByList = common.ToSelectList(OutputBusinessLogic.getInstance().getSortByDDL(), "ID", "NAME", string.Empty);
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(string Submit, HistoryViewModels model)
        {
            model.TodaysJournal = Journals(model);
            ViewBag.AccountList = common.ToSelectList(AccountDetailsBusinessLogic.getInstance().getAccountDetailDDL(), "ID", "NAME", model.Account);
            ViewBag.BankFacilityList = common.ToSelectList(BankFacilityBusinessLogic.getInstance().getBankFacilityDDL(), "ID", "NAME", model.BankAccount);
            ViewBag.SortByList = common.ToSelectList(OutputBusinessLogic.getInstance().getSortByDDL(), "ID", "NAME", model.SortBy);

            if (!String.IsNullOrEmpty(Submit))
            {
                if (Submit.Equals("PDF"))
                {
                    GeneratePdf(model);
                }
                else if (Submit.Equals("Excel"))
                {
                    GenerateExcel(model);
                }
                else if (Submit.Equals("Print"))
                {

                }
            }

            return View(model);
        }

        private PagedList<HistoryViewModels> Journals(HistoryViewModels model)
        {
            var page = new PagedList<HistoryViewModels>();
            page.Content = HistoryBusinessLogic.getInstance().TodaysJournal(model);
            return page;
        }

        private void GeneratePdf(HistoryViewModels model)
        {
            MemoryStream ms = new MemoryStream();
            iTextSharp.text.Rectangle rec = new iTextSharp.text.Rectangle(PageSize.A4);
            rec.BackgroundColor = new BaseColor(System.Drawing.Color.Olive);
            Document doc = new Document(rec);
            doc.SetPageSize(iTextSharp.text.PageSize.A4);
            PdfWriter writer = PdfWriter.GetInstance(doc, ms);
            doc.Open();

            BaseFont arial = BaseFont.CreateFont(Server.MapPath(fontPath) + "ARIALN.TTF", BaseFont.CP1252, BaseFont.NOT_EMBEDDED);

            Paragraph prgHeading = new Paragraph();
            prgHeading.Alignment = Element.ALIGN_CENTER;
            prgHeading.Add(new Chunk("DIPO INVESTAMA", new iTextSharp.text.Font(arial, 16, iTextSharp.text.Font.BOLD, BaseColor.BLACK)));
            doc.Add(prgHeading);

            prgHeading = new Paragraph();
            prgHeading.Alignment = Element.ALIGN_CENTER;
            prgHeading.Add(new Chunk(" ", new iTextSharp.text.Font(arial, 16, iTextSharp.text.Font.BOLD, BaseColor.BLACK)));
            doc.Add(prgHeading);

            PdfPTable table = new PdfPTable(7);
            table.WidthPercentage = 100;
            table.SetWidthPercentage(new float[] { 15, 15, 15, 25, 10, 10, 10 }, new iTextSharp.text.Rectangle(doc.PageSize.Width / 6, doc.PageSize.Height));

            PdfPCell cell = new PdfPCell();
            cell.Phrase = new Phrase("Date"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            cell = new PdfPCell();
            cell.Phrase = new Phrase("Account"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            cell = new PdfPCell();
            cell.Phrase = new Phrase("Bank"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            cell = new PdfPCell();
            cell.Phrase = new Phrase("Description"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            cell = new PdfPCell();
            cell.Phrase = new Phrase("Cash Out"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            cell = new PdfPCell();
            cell.Phrase = new Phrase("Cash In"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            cell = new PdfPCell();
            cell.Phrase = new Phrase("Balance"
                        , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
            cell.HorizontalAlignment = Element.ALIGN_LEFT;
            cell.Border = 1;
            table.AddCell(cell);

            foreach (var item in model.TodaysJournal.Content)
            {
                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.Date
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);

                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.Account
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);

                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.BankAccount
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);

                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.Description
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);

                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.CashIn
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);

                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.CashOut
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);

                cell = new PdfPCell();
                cell.Phrase = new Phrase(item.Balance
                            , new iTextSharp.text.Font(arial, 9, iTextSharp.text.Font.BOLD, new BaseColor(System.Drawing.ColorTranslator.FromHtml("#000000"))));
                cell.HorizontalAlignment = Element.ALIGN_LEFT;
                cell.Border = 1;
                table.AddCell(cell);
            }

            doc.Add(table);
            doc.Close();

            byte[] result = ms.ToArray();

DIPO_INVESTAMA/Views/History/Index.cshtml
@model DIPO_INVESTAMA.Models.HistoryViewModels
@{
    ViewBag.Title = "Today's Journal";
}

@using (Html.BeginForm("Index", "History"))
{
    if (TempData["Error"] != null)
    {
        <div class="alert alert-warning" style="margin:10px">
            <p><i class="fa fa-warning"></i> @TempData["Error"].ToString()</p>
        </div>
    }
    if (TempData["Success"] != null)
    {
        <div class="alert alert-success" style="margin:10px">
            <strong>Success!</strong> @TempData["Success"].ToString()
        </div>
    }

    <div class="box box-primary body-box-primary">
        <div class="box-header with-border">
            <h3 class="box-title Poppins-Bold font-white">Quick Example</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form">
            <div class="box-body Poppins-Regular font-white">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                @Html.TextBoxFor(model => model.Date, new { @class = "form-control pull-left", @placeholder = "Date", autocomplete = "off"})
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            @Html.DropDownListFor(model => model.Account, ViewBag.AccountList as SelectList, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            @Html.DropDownListFor(model => model.BankAccount, ViewBag.BankFacilityList as SelectList, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            @Html.DropDownListFor(model => model.SortBy, ViewBag.SortByList as SelectList, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-lg-1">
                        <button type="submit" name="Submit" value="Excel"><img src="~/Assets/icon/Group 1290.png" width="30" height="30" /></button>
                        @*<a type="submit" name="Submit" value="PDF"><img src="~/Assets/icon/pdf.png" width="30" height="30"/></a>
                        <button type="submit" name="Submit" value="Print"><img src="~/Assets/icon/print.png" width="30" height="30" /></button>*@
                    </div>
                </div>
            </div>
        </form>
    </div>

    @Html.Partial("PartialViews/Journals", Model.TodaysJournal)
}

<script type="text/javascript">
    $(function()
    {
        $('#Date').daterangepicker({
            autoclose: true
        })
        //$('#Date').val("");
        $("#Date").on("change", function () {
            var url = "@Url.Action("Index","History")";
            window.location.href = url + "?sd=" + $("#Date").val().split("-")[0] + "&ed=" + $("#Date").val().split("-")[1] + "&acc=" + $("#Account").val() + "&bnk=" + $("#BankAccount").val() + "&srt=" + $("#SortBy").val()
            @*var data = { Date: $("#Date").val(), Account: $("#Account").val(), BankAccount: $("#BankAccount").val(), SortBy: $("#SortBy").val() };

            $.ajax(
            {
                url: "@Url.Action("Index", "Output")",
                type: 'POST',
                data: { model: data },
                success: function (response) {

                },
                error: function () {
                    alert("error");
                }
            });*@
        });

        $("#Account").on("change", function () {
            var url = "@Url.Action("Index","History")";
            window.location.href = url + "?sd=" + $("#Date").val().split("-")[0] + "&ed=" + $("#Date").val().split("-")[1] + "&acc=" + $("#Account").val() + "&bnk=" + $("#BankAccount").val() + "&srt=" + $("#SortBy").val()
            @*var data = { Date: $("#Date").val(), Account: $("#Account").val(), BankAccount: $("#BankAccount").val(), SortBy: $("#SortBy").val() };

            $.ajax(
            {
                url: "@Url.Action("Index", "Output")",
                type: 'POST',
            data: { model: data },
            success: function (response) {

            },
            error: function () {
                alert("error");
            }
        });*@
        });

        $("#BankAccount").on("change", function () {
            var url = "@Url.Action("Index","History")";
            window.location.href = url + "?sd=" + $("#Date").val().split("-")[0] + "&ed=" + $("#Date").val().split("-")[1] + "&acc=" + $("#Account").val() + "&bnk=" + $("#BankAccount").val() + "&srt=" + $("#SortBy").val()
            @*var data = { Date: $("#Date").val(), Account: $("#Account").val(), BankAccount: $("#BankAccount").val(), SortBy: $("#SortBy").val() };

            $.ajax(
            {
                url: "@Url.Action("Index", "Output")",
                type: 'POST',
            data: { model: data },
            success: function (response) {

            },
            error: function () {
                alert("error");
            }
        });*@
    });

        $("#SortBy").on("change", function () {
            var url = "@Url.Action("Index","History")";
            window.location.href = url + "?sd=" + $("#Date").val().split("-")[0] + "&ed=" + $("#Date").val().split("-")[1] + "&acc=" + $("#Account").val() + "&bnk=" + $("#BankAccount").val() + "&srt=" + $("#SortBy").val()
            @*var data = { Date: $("#Date").val(), Account: $("#Account").val(), BankAccount: $("#BankAccount").val(), SortBy: $("#SortBy").val() };

            $.ajax(
            {
                url: "@Url.Action("Index", "Output")",
                type: 'POST',
            data: { model: data },
            success: function (response) {

            },
            error: function () {
                alert("error");
            }
        });*@
    });
    })
</script>